{
 "title": "Quick Look - Log Time",
 "description": "A dashboard designed for a quick readout by those working in the pit;",
 "time": { "from": "2023-04-18T01:20:50.034Z", "to": "2023-04-18T01:30:50.034Z" },
 "templating": {
  "list": [
   {
    "name": "Timestamp",
    "query": "SELECT EXTRACT(EPOCH FROM log_timestamp)::bigint AS __value, TO_CHAR(log_timestamp, 'Mon DD YYYY, HH24:MI:SS') AS __text FROM metrics GROUP BY log_timestamp ORDER BY log_timestamp DESC;"
   }
  ]
 },
 "panels": [
  { "title": "Current Time", "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Next Queue",
   "type": "grafana-clock-panel",
   "description": "Stop work and begin queueing at this time.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 }
  },
  {
   "title": "Metrics",
   "type": "heywesty-trafficlight-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \"group\", MAX(stoplight) FROM metrics WHERE EXTRACT(EPOCH FROM log_timestamp) = ${Timestamp} GROUP BY \"group\", log_timestamp LIMIT 50"
    }
   ]
  },
  {
   "title": "Swerve Warnings",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT metric AS \"Metric\", stoplight AS \"Stoplight\", value AS \"Value\" FROM metrics WHERE \"group\" = 'swerve' AND EXTRACT(EPOCH FROM log_timestamp) = ${Timestamp} AND stoplight >= 1 GROUP BY metric, value, stoplight LIMIT 50"
    }
   ]
  },
  {
   "title": "Flywheel Warnings",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT metric AS \"Metric\", stoplight AS \"Stoplight\", value AS \"Value\" FROM metrics WHERE \"group\" = 'flywheel' AND EXTRACT(EPOCH FROM log_timestamp) = ${Timestamp} AND stoplight >= 1 ORDER BY stoplight DESC, metric LIMIT 50"
    }
   ]
  },
  {
   "title": "Turret Warnings",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT metric AS \"Metric\", stoplight AS \"Stoplight\", value AS \"Value\" FROM metrics WHERE \"group\" = 'turret' AND EXTRACT(EPOCH FROM log_timestamp) = ${Timestamp} AND stoplight >= 1 ORDER BY stoplight DESC, metric LIMIT 50"
    }
   ]
  },
  {
   "title": "Hood Warnings",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT metric AS \"Metric\", stoplight AS \"Stoplight\", value AS \"Value\" FROM metrics WHERE \"group\" = 'hood' AND EXTRACT(EPOCH FROM log_timestamp) = ${Timestamp} AND stoplight >= 1 ORDER BY stoplight DESC, metric LIMIT 50"
    }
   ]
  },
  {
   "title": "Climber Warnings",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT metric AS \"Metric\", stoplight AS \"Stoplight\", value AS \"Value\" FROM metrics WHERE \"group\" = 'climber' AND EXTRACT(EPOCH FROM log_timestamp) = ${Timestamp} AND stoplight >= 1 ORDER BY stoplight DESC, metric LIMIT 50"
    }
   ]
  },
  {
   "title": "Intake Arm Warnings",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT metric AS \"Metric\", stoplight AS \"Stoplight\", value AS \"Value\" FROM metrics WHERE \"group\" = 'intake_arm' AND EXTRACT(EPOCH FROM log_timestamp) = ${Timestamp} AND stoplight >= 1 ORDER BY stoplight DESC, metric LIMIT 50"
    }
   ]
  },
  {
   "title": "Intake Wheels Warnings",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT metric AS \"Metric\", stoplight AS \"Stoplight\", value AS \"Value\" FROM metrics WHERE \"group\" = 'intake_wheels' AND EXTRACT(EPOCH FROM log_timestamp) = ${Timestamp} AND stoplight >= 1 ORDER BY stoplight DESC, metric LIMIT 50"
    }
   ]
  },
  {
   "title": "Indexer Warnings",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "rawSql": "SELECT metric AS \"Metric\", stoplight AS \"Stoplight\", value AS \"Value\" FROM metrics WHERE \"group\" = 'indexer' AND EXTRACT(EPOCH FROM log_timestamp) = ${Timestamp} AND stoplight >= 1 ORDER BY stoplight DESC, metric LIMIT 50"
    }
   ]
  },
  {
   "title": "Chamber Warnings",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "rawSql": "SELECT metric AS \"Metric\", stoplight AS \"Stoplight\", value AS \"Value\" FROM metrics WHERE \"group\" = 'chamber' AND EXTRACT(EPOCH FROM log_timestamp) = ${Timestamp} AND stoplight >= 1 ORDER BY stoplight DESC, metric LIMIT 50"
    }
   ]
  },
  {
   "title": "Power Warnings",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "rawSql": "SELECT metric AS \"Metric\", stoplight AS \"Stoplight\", value AS \"Value\" FROM metrics WHERE \"group\" = 'power' AND EXTRACT(EPOCH FROM log_timestamp) = ${Timestamp} AND stoplight >= 1 ORDER BY stoplight DESC, metric LIMIT 50"
    }
   ]
  },
  {
   "title": "Imu Warnings",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "rawSql": "SELECT metric AS \"Metric\", stoplight AS \"Stoplight\", value AS \"Value\" FROM metrics WHERE \"group\" = 'imu' AND EXTRACT(EPOCH FROM log_timestamp) = ${Timestamp} AND stoplight >= 1 ORDER BY stoplight DESC, metric LIMIT 50"
    }
   ]
  }
 ]
}